sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 8.1
    - php: 8.2

before_install:
  - composer self-update

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest --prefer-stable; fi
  - if [ "$deps" = "" ]; then composer install; fi
  - vendor/bin/simple-phpunit install

script:
  - vendor/bin/simple-phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
